### ISSUE TITLE
Create SSM using PCA - not converged exception

### ISSUE THREAD

**Issue by madsendennis** [unibas-gravis/scalismo#284]
The default Pivoted Cholesky stopping criterion (PivotedCholesky.RelativeTolerance(0)) can experience a NotConvergedException when using a very small dataset. 

The following code will in most of the runs throw an error when using the default stopping criteria. If the stopping criteria instead is set to be numberOfEigenfunctions = data-1, then it consistently works. 

```scala
val model = StatismoIO.readStatismoMeshModel(new File("model2017-1_bfm_nomouth-2500.h5")).get

val ref = model.referenceMesh

val data = (1 to 3).map(f => model.sample())

println(s"data length: ${data.length}")
val dc = DataCollection.fromMeshSequence(referenceMesh = ref, registeredMeshes = data)._1.get
val dcGpa = DataCollection.gpa(dc)
StatisticalMeshModel.createUsingPCA(dcGpa, NumberOfEigenfunctions.apply(data.length-1)).get
println("pca 1 computed")
StatisticalMeshModel.createUsingPCA(dcGpa).get // NotConvergedException
println("pca 2 computed")
```
Full error message (might need to run multiple times to get the error message - depends on the samples that are drawn from the BFM)
```
Exception in thread "main" breeze.linalg.NotConvergedException: 
	at breeze.linalg.svd$.breeze$linalg$svd$$doSVD_Double(svd.scala:110)
	at breeze.linalg.svd$Svd_DM_Impl$.apply(svd.scala:40)
	at breeze.linalg.svd$Svd_DM_Impl$.apply(svd.scala:39)
	at breeze.generic.UFunc.apply(UFunc.scala:48)
	at breeze.generic.UFunc.apply$(UFunc.scala:46)
	at breeze.linalg.svd$.apply(svd.scala:23)
	at scalismo.numerics.PivotedCholesky$.computeApproximateEigGeneric(PivotedCholesky.scala:193)
	at scalismo.numerics.PivotedCholesky$.computeApproximateEig(PivotedCholesky.scala:216)
	at scalismo.statisticalmodel.DiscreteLowRankGaussianProcess$.createUsingPCA(DiscreteLowRankGaussianProcess.scala:457)
	at scalismo.statisticalmodel.StatisticalMeshModel$.createUsingPCA(StatisticalMeshModel.scala:315)
	at scalismo.statisticalmodel.StatisticalMeshModel$.createUsingPCA(StatisticalMeshModel.scala:300)
	at apps.bfm.PCAtest$.main(PCAtest.scala:36)
	at apps.bfm.PCAtest.main(PCAtest.scala)
```

**Comment by thogerig** [comment]
Dennis, thanks for pointing this out. There seems to be an issue in the pivoted Cholesky. I will investigate this further.
